### ISSUE TITLE
Error connecting to database

### ISSUE THREAD

**Issue by JobCollins** [KishinNext/querycrafter#6]
Hey,

I am trying to run
`docker compose build --no-cache && docker compose up`

but I get the following error

```
Could not import azure.core python package.
ERROR:root:Error connecting to database: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
```
is there a workaround to this?

I am running this on a MacOS Monterey Version 12.6.3 terminal

**Comment by JobCollins** [comment]
I have fixed the above issue by changing
```
database:
    url: 'postgresql://postgres:postgres@localhost:5432/Adventureworks'
```
to
```
database:
    url: 'postgresql://postgres:postgres@postgres:5432/Adventureworks'
```
in the `development.yaml` file.

However, now I am getting the following output and nothing is happening beyond this
```
{"asctime": "2023-08-21 10:13:00,977", "name": "root", "message": "current path /app/utils", "timestamp": "2023-08-21T10:13:00.977578+00:00", "status": "DEBUG"}
```

clicking on http://localhost:8080/ returns 

```
{
"detail": "Not Found"
}
```

**Comment by KishinNext** [comment]
Hey @JobCollins sorry for the late reply. I think there's a documentation issue with the app. I've created a new [PR](https://github.com/KishinNext/querycrafter/pull/7) to enhance the docs, making it more step-by-step. 

Remember, the URL link is for the database you want to pull data from or create dashboards with. And a quick heads-up: avoid using a user database with admin privileges 😄. I've left the Pull Request open, so if you find anything or have insights that could help with the app's setup, feel free to add!

**Comment by JobCollins** [comment]
Hey @KishinNext, thanks for the reply. I have been afk and now coming back. I see this is closed, but I am wondering if this is the expected output if the app runs correctly,

`{"asctime": "2023-08-21 10:13:00,977", "name": "root", "message": "current path /app/utils", "timestamp": "2023-08-21T10:13:00.977578+00:00", "status": "DEBUG"}`

I expected a bit more 😃

**Comment by KishinNext** [comment]
Hello @JobCollins, Yes, that's the expected output when the app ran correctly (a not-so-clear workflow, by the way 😅) but you can now use the app to run your queries. Ideally, if you're working locally, you can use **ngrok** to connect your environment to the Slack application and start testing the tool.
